begin transaction;

INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Австрийская');       
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Азербайджанская');   
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Американская');      
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Английская');        
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Арабская');          
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Армянская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Африканская');       
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Болгарская');        
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Бразильская');       
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Греческая');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Грузинская');        
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Еврейская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Европейская');       
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Индийская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Испанская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Итальянская');       
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Кавказская');        
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Китайская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Корейская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Кубинская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Латиноамериканская');
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Мексиканская');      
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Немецкая');          
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Паназиатская');      
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Русская');           
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Средиземноморская'); 
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Тайваньская');       
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Тайская');           
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Турецкая');          
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Тибетская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Узбекская');         
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Украинская');        
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Французская');       
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Югославская');       
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Японская');          
INSERT INTO cuisine (deleted,modified,name) VALUES (false,now(),'Халяль');            

INSERT INTO AverageCheck (deleted,modified,amount,name) VALUES (false,now(), 700,'до 700 рублей');
INSERT INTO AverageCheck (deleted,modified,amount,name) VALUES (false,now(),1500,'от 700 до 1500 рублей');
INSERT INTO AverageCheck (deleted,modified,amount,name) VALUES (false,now(),2500,'от 1500 до 2500 рублей');
INSERT INTO AverageCheck (deleted,modified,amount,name) VALUES (false,now(),1000000,'более 2500 рублей');

INSERT INTO parking (deleted,modified,name) VALUES (false,now(),'парковка заведения');
INSERT INTO parking (deleted,modified,name) VALUES (false,now(),'публичный паркинг');
INSERT INTO parking (deleted,modified,name) VALUES (false,now(),'нет парковки');
INSERT INTO parking (deleted,modified,name) VALUES (false,now(),'валет-сервис');

--actiontype,actionsubtype
INSERT INTO actiontype (deleted,modified,name) VALUES (false,now(),'Скидка');
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'5%',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'10%',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'15%',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'20%',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'25%',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'30%',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'35%',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'50%',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'скидка',(select max(id) from actiontype));

INSERT INTO actiontype (deleted,modified,name) VALUES (false,now(),'Подарок');
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'1=2',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'1+1=3',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'подарок',(select max(id) from actiontype));

INSERT INTO actiontype (deleted,modified,name) VALUES (false,now(),'Счастливые часы');
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Завтрак',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Бизнес-ланч',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Счастливые часы',(select max(id) from actiontype));

INSERT INTO actiontype (deleted,modified,name) VALUES (false,now(),'Групповые');
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'групповые',(select max(id) from actiontype));

INSERT INTO actiontype (deleted,modified,name) VALUES (false,now(),'Праздник');
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Новый год',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'День всех влюбленных',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'День защитника отечества',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Женский день',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Масленица',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Майские праздники',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'День победы',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'День России',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Великий пост',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Пасха',(select max(id) from actiontype));
--эта строчка ('Ресторана') появилась позже, убедитесь что в МП она будет иметь тот-же ID
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Ресторана',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Праздник',(select max(id) from actiontype));
--а эта строчка появилась спустя месяц, когда 'Ресторана' решили убрать
update actionsubtype set deleted = true where name= 'Ресторана' and actiontype_id = 5;

INSERT INTO actiontype (deleted,modified,name) VALUES (false,now(),'Специальная акция');
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Специальная акция',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Блюдо дня',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'День рождения',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Студенческая скидка',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Возьми с собой',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Для пар',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Мероприятия',(select max(id) from actiontype));
INSERT INTO actionsubtype (deleted,modified,name,actiontype_id) VALUES (false,now(),'Новинка',(select max(id) from actiontype));
------------------------------

INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Авиамоторная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Автозаводская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Академическая');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Александровский сад');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Алексеевская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Алма-Атинская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Алтуфьево');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Аннино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Арбатская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Аэропорт');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Бабушкинская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Багратионовская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Баррикадная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Бауманская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Беговая');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Белорусская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Беляево');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Бибирево');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Библиотека имени Ленина');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Битцевский парк');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Борисово');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Боровицкая');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Ботанический сад');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Братиславская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Бульвар адмирала Ушакова');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Бульвар Дмитрия Донского');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Бульвар Рокоссовского');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Бунинская аллея');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Варшавская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'ВДНХ');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Владыкино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Водный стадион');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Войковская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Волгоградский проспект');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Волжская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Волоколамская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Воробьёвы горы');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Выставочная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Выхино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Деловой центр');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Динамо');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Дмитровская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Добрынинская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Домодедовская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Достоевская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Дубровка');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Жулебино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Зябликово');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Измайловская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Калужская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Кантемировская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Каховская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Каширская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Киевская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Китай-город');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Кожуховская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Коломенская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Комсомольская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Коньково');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Котельники');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Красногвардейская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Краснопресненская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Красносельская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Красные ворота');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Крестьянская застава');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Кропоткинская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Крылатское');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Кузнецкий мост');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Кузьминки');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Кунцевская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Курская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Кутузовская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Ленинский проспект');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Лермонтовский проспект');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Лесопарковая');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Лубянка');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Люблино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Марксистская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Марьина роща');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Марьино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Маяковская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Медведково');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Международная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Менделеевская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Митино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Молодёжная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Мякинино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Нагатинская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Нагорная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Нахимовский проспект');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Новогиреево');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Новокосино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Новокузнецкая');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Новослободская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Новоясеневская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Новые Черёмушки');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Октябрьская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Октябрьское поле');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Орехово');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Отрадное');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Охотный ряд');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Павелецкая');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Парк культуры');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Парк Победы');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Партизанская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Первомайская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Перово');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Петровско-Разумовская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Печатники');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Пионерская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Планерная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Площадь Ильича');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Площадь Революции');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Полежаевская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Полянка');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Пражская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Преображенская площадь');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Пролетарская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Проспект Вернадского');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Проспект Мира');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Профсоюзная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Пушкинская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Пятницкое шоссе');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Речной вокзал');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Рижская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Римская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Рязанский проспект');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Савёловская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Свиблово');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Севастопольская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Семёновская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Серпуховская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Славянский бульвар');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Смоленская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Сокол');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Сокольники');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Спартак');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Спортивная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Сретенский бульвар');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Строгино');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Студенческая');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Сухаревская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Сходненская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Таганская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Тверская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Театральная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Текстильщики');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Тёплый Стан');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Тимирязевская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Третьяковская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Тропарёво');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Трубная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Тульская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Тургеневская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Тушинская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Улица 1905 года');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Улица академика Янгеля');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Улица Горчакова');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Улица Скобелевская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Улица Старокачаловская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Университет');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Филёвский парк');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Фили');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Фрунзенская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Царицыно');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Цветной бульвар');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Черкизовская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Чертановская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Чеховская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Чистые пруды');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Чкаловская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Шаболовская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Шипиловская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Шоссе Энтузиастов');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Щёлковская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Щукинская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Электрозаводская');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Юго-Западная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Южная');
INSERT INTO subway (deleted,modified,name) VALUES (false,now(),'Ясенево');
-------------------------

commit;
