
CREATE TABLE restaurant (
    id bigserial primary key,
    deleted boolean NOT NULL,
    modified Timestamp NOT NULL,
    name character varying(80) NOT NULL,
    description text NOT NULL,
    status character varying(20) NOT NULL,
    cuisine_id1 bigint references cuisine(id) NOT NULL,
    cuisine_id2 bigint references cuisine(id) NULL,
    cuisine_id3 bigint references cuisine(id) NULL,
    address character varying(128) NOT NULL,
    coord_lat double precision NOT NULL,
    coord_lon double precision NOT NULL,
    subway_id bigint references subway(id) NOT NULL,
    phone character varying(40) NOT NULL,
    website character varying(128) NOT NULL,
    averagecheck_id bigint references averagecheck(id) NOT NULL,
    wifi boolean NOT NULL,
    parking_id bigint references parking(id) NOT NULL,
    kids_menu boolean NOT NULL,
    entertainments character varying(128) NOT NULL,
    cards_visa       boolean NOT NULL,
    cards_mastercard boolean NOT NULL,
    cards_maestro    boolean NOT NULL,
    cards_unionpay   boolean NOT NULL,
    cards_visaelectron    boolean NOT NULL,
    cards_americanexpress boolean NOT NULL,
    cards_dinersclub      boolean NOT NULL,
    cards_pro100          boolean NOT NULL,
    workday_monday    boolean NOT NULL,
    workday_tuesday   boolean NOT NULL,
    workday_wednesday boolean NOT NULL,
    workday_thursday  boolean NOT NULL,
    workday_friday    boolean NOT NULL,
    workday_saturday  boolean NOT NULL,
    workday_sunday    boolean NOT NULL,
    workday_starttime character varying(5) NOT NULL,
    workday_endtime   character varying(5) NOT NULL,
    holiday_starttime character varying(5) NOT NULL,
    holiday_endtime   character varying(5) NOT NULL,

    legal_name character varying(160) NOT NULL,
    legal_address character varying(160) NOT NULL,
    director character varying(60) NOT NULL,
    OGRN character varying(13) NOT NULL,
    INN character varying(12) NOT NULL,
    KPP character varying(9) NOT NULL,
    bank character varying(160) NOT NULL,
    BIC character varying(9) NOT NULL,
    cust_account character varying(20) NOT NULL,
    corr_account character varying(20) NOT NULL,

    partner_id bigint references partner(id) NOT NULL,

    cards_jcb boolean NOT NULL,
    cards_mir boolean NOT NULL
);

create unique index ndx_restaurant_name on restaurant (name);
create index ndx_restaurant_partner_id on restaurant (partner_id);

